<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\NaturezaDespesa;

class NaturezaDespesaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        NaturezaDespesa::create([ 'codigo' => '313041', 'nome' => 'Contribuições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '318004', 'nome' => 'Contratação por Tempo Determinado', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '318034', 'nome' => 'Outras Despesas de Pessoal Decorrentes de Contratos de Terceirização', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319001', 'nome' => 'Aposentadorias e Reformas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319003', 'nome' => 'Pensões', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319004', 'nome' => 'Contratação por Tempo Determinado', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319007', 'nome' => 'Contribuição a Entidades Fechadas de Previdência', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319008', 'nome' => 'Outros Benefícios Assistenciais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319009', 'nome' => 'Salário-Família', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319011', 'nome' => 'Vencimentos e Vantagens Fixas - Pessoal Civil', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319012', 'nome' => 'Vencimentos e Vantagens Fixas - Pessoal Militar', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319013', 'nome' => 'Obrigações Patronais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319016', 'nome' => 'Outras Despesas Variáveis - Pessoal Civil', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319017', 'nome' => 'Outras Despesas Variáveis - Pessoal Militar', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319034', 'nome' => 'Outras Despesas de Pessoal decorrentes de Contratos de Terceirização', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319067', 'nome' => 'Depósitos Compulsórios', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319091', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319094', 'nome' => 'Indenizações e Restituições Trabalhistas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319096', 'nome' => 'Ressarcimento de Despesas de Pessoal Requisitado', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319104', 'nome' => 'Contratação por Tempo Determinado', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319113', 'nome' => 'Contribuições Patronais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319191', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319192', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319194', 'nome' => 'Indenizações e Restituições Trabalhistas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319196', 'nome' => 'Ressarcimento de Despesas de Pessoal Requisitado', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '329021', 'nome' => 'Juros sobre a Dívida por Contrato', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '329022', 'nome' => 'Outros Encargos sobre a Dívida por Contrato', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '329023', 'nome' => 'Juros, Deságios e Descontos da Dívida Mobiliária', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '329024', 'nome' => 'Outros Encargos sobre a Dívida Mobiliária', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '329025', 'nome' => 'Encargos sobre Operações de Crédito por Antecipação da Receita', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '329091', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '329092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '329093', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '332014', 'nome' => 'Diárias - Civil', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '332030', 'nome' => 'Material de Consumo', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '332035', 'nome' => 'Serviços de Consultoria', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '332036', 'nome' => 'Outros Serviços de Terceiros - Pessoa Física', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '332039', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '332041', 'nome' => 'Contribuições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333014', 'nome' => 'Diárias - Civil', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333018', 'nome' => 'Auxílio Financeiro a Estudantes', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333020', 'nome' => 'Auxílio Financeiro a Pesquisadores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333030', 'nome' => 'Material de Consumo', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333033', 'nome' => 'Passagens e Despesas com Locomoção', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333035', 'nome' => 'Serviços de Consultoria', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333036', 'nome' => 'Outros Serviços de Terceiros - Pessoa Física', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333039', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333041', 'nome' => 'Contribuições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333043', 'nome' => 'Subvenções Sociais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333047', 'nome' => 'Obrigações Tributárias e Contributivas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333081', 'nome' => 'Distribuição Constitucional ou Legal de Receitas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '333093', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334014', 'nome' => 'Diárias - Civil', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334018', 'nome' => 'Auxílio Financeiro a Estudantes', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334030', 'nome' => 'Material de Consumo', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334033', 'nome' => 'Passagens e Despesas com Locomoção', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334035', 'nome' => 'Serviços de Consultoria', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334036', 'nome' => 'Outros Serviços de Terceiros - Pessoa Física', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334039', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334041', 'nome' => 'Contribuições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334043', 'nome' => 'Subvenções Sociais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334047', 'nome' => 'Obrigações Tributárias e Contributivas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334081', 'nome' => 'Distribuição Constitucional ou Legal de Receitas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '334093', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335014', 'nome' => 'Diárias - Civil', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335018', 'nome' => 'Auxílio Financeiro a Estudantes', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335020', 'nome' => 'Auxílio Financeiro a Pesquisadores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335030', 'nome' => 'Material de Consumo', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335031', 'nome' => 'Premiações Culturais, Artísticas, Científicas, Desportivas e Outras', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335033', 'nome' => 'Passagens e Despesas com Locomoção', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335035', 'nome' => 'Serviços de Consultoria', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335036', 'nome' => 'Outros Serviços de Terceiros - Pessoa Física', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335039', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335041', 'nome' => 'Contribuições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335043', 'nome' => 'Subvenções Sociais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335047', 'nome' => 'Obrigações Tributárias e Contributivas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '335092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '336041', 'nome' => 'Contribuições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '336045', 'nome' => 'Equalização de Preços e Taxas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '336092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '337041', 'nome' => 'Contribuições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338004', 'nome' => 'Contratação por Tempo Determinado', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338014', 'nome' => 'Diárias - Civil', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338030', 'nome' => 'Material de Consumo', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338033', 'nome' => 'Passagens e Despesas com Locomoção', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338035', 'nome' => 'Serviços de Consultoria', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338036', 'nome' => 'Outros Serviços de Terceiros - Pessoa Física', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338037', 'nome' => 'Locação de Mão-de-Obra', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338039', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338041', 'nome' => 'Contribuições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '338092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339001', 'nome' => 'Aposentadorias e Reformas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339003', 'nome' => 'Pensões', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339004', 'nome' => 'Contratação por Tempo Determinado', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339005', 'nome' => 'Outros Benefícios Previdenciários', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339006', 'nome' => 'Benefício Mensal ao Deficiente e ao Idoso', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339008', 'nome' => 'Outros Benefícios Assistenciais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339009', 'nome' => 'Salário-Família', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339010', 'nome' => 'Outros Benefícios de Natureza Social', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339014', 'nome' => 'Diárias - Civil', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339015', 'nome' => 'Diárias - Militar', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339018', 'nome' => 'Auxílio Financeiro a Estudantes', 'tipo' => 'Custeio', 'comentario' => 'QTD.1: Quantidade de pessoas <br> QTD.2: Quantidade de passagens']);
NaturezaDespesa::create([ 'codigo' => '339019', 'nome' => 'Auxílio-Fardamento', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339020', 'nome' => 'Auxílio Financeiro a Pesquisadores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339026', 'nome' => 'Obrigações Decorrentes de Política Monetária', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339027', 'nome' => 'Encargos pela Honra de Avais, Garantias, Seguros e Similares', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339028', 'nome' => 'Remuneração de Cotas de Fundos Autárquicos', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339030', 'nome' => 'Material de Consumo', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339031', 'nome' => 'Premiações Culturais, Artísticas, Científicas, Desportivas e Outras', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339032', 'nome' => 'Material de Distribuição Gratuita', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339033', 'nome' => 'Passagens e Despesas com Locomoção', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339035', 'nome' => 'Serviços de Consultoria', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339036', 'nome' => 'Outros Serviços de Terceiros - Pessoa Física', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339037', 'nome' => 'Locação de Mão-de-Obra', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339038', 'nome' => 'Arrendamento Mercantil', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339039', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339041', 'nome' => 'Contribuições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339045', 'nome' => 'Equalização de Preços e Taxas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339046', 'nome' => 'Auxílio-Alimentação', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339047', 'nome' => 'Obrigações Tributárias e Contributivas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339048', 'nome' => 'Outros Auxílios Financeiros a Pessoas Físicas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339049', 'nome' => 'Auxílio-Transporte', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339067', 'nome' => 'Depósitos Compulsórios', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339091', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339093', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339095', 'nome' => 'Indenização pela Execução de Trabalhos de Campo', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339104', 'nome' => 'Contratação por Tempo Determinado', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339128', 'nome' => 'Remuneração de Cotas de Fundos Autárquicos', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339130', 'nome' => 'Material de Consumo', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339132', 'nome' => 'Material de Distribuição Gratuita', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339135', 'nome' => 'Serviços de Consultoria', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339139', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339147', 'nome' => 'Obrigações Tributárias e Contributivas', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339162', 'nome' => 'Aquisição de Produtos para Revenda', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339191', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339192', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339193', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '339196', 'nome' => 'Ressarcimento de Despesas de Pessoal Requisitado', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '442041', 'nome' => 'Contribuições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '442042', 'nome' => 'Auxílios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '442051', 'nome' => 'Obras e Instalações', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '442052', 'nome' => 'Equipamentos e Material Permanente', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '442092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '442093', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '443020', 'nome' => 'Auxílio Financeiro a Pesquisadores', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '443041', 'nome' => 'Contribuições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '443042', 'nome' => 'Auxílios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '443051', 'nome' => 'Obras e Instalações', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '443052', 'nome' => 'Equipamentos e Material Permanente', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '443092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '443093', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '444014', 'nome' => 'Diárias - Civil', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '444041', 'nome' => 'Contribuições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '444042', 'nome' => 'Auxílios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '444051', 'nome' => 'Obras e Instalações', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '444052', 'nome' => 'Equipamentos e Material Permanente', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '444092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '445014', 'nome' => 'Diárias - Civil', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '445030', 'nome' => 'Material de Consumo', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '445036', 'nome' => 'Outros Serviços de Terceiros - Pessoa Física', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '445039', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '445041', 'nome' => 'Contribuições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '445042', 'nome' => 'Auxílios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '445047', 'nome' => 'Obrigações Tributárias e Contributivas', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '445051', 'nome' => 'Obras e Instalações', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '445052', 'nome' => 'Equipamentos e Material Permanente', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '446041', 'nome' => 'Contribuições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '446042', 'nome' => 'Auxílios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '447041', 'nome' => 'Contribuições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '447042', 'nome' => 'Auxílios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '448041', 'nome' => 'Contribuições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '448042', 'nome' => 'Auxílios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '448051', 'nome' => 'Obras e Instalações', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '448052', 'nome' => 'Equipamentos e Material Permanente', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449004', 'nome' => 'Contratação por Tempo Determinado', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449014', 'nome' => 'Diárias - Civil', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449015', 'nome' => 'Diárias - Militar', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449017', 'nome' => 'Outras Despesas Variáveis - Pessoal Militar', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449018', 'nome' => 'Auxílio Financeiro a Estudantes', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449020', 'nome' => 'Auxílio Financeiro a Pesquisadores', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449030', 'nome' => 'Material de Consumo', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449033', 'nome' => 'Passagens e Despesas com Locomoção', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449035', 'nome' => 'Serviços de Consultoria', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449036', 'nome' => 'Outros Serviços de Terceiros - Pessoa Física', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449037', 'nome' => 'Locação de Mão-de-Obra', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449039', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449047', 'nome' => 'Obrigações Tributárias e Contributivas', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449051', 'nome' => 'Obras e Instalações', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449052', 'nome' => 'Equipamentos e Material Permanente', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449061', 'nome' => 'Aquisição de Imóveis', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449091', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449093', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449139', 'nome' => 'Outros Serviços de Terceiros - Pessoa Jurídica', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449147', 'nome' => 'Obrigações Tributárias e Contributivas', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449151', 'nome' => 'Obras e Instalações', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449152', 'nome' => 'Equipamentos e Material Permanente', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '449191', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '453041', 'nome' => 'Contribuições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '453042', 'nome' => 'Auxílios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '453061', 'nome' => 'Aquisição de Imóveis', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '453064', 'nome' => 'Aquisição de Títulos Representativos de Investimento já Integralizado', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '453065', 'nome' => 'Constituição ou Aumento de Investimento de Empresas', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '453066', 'nome' => 'Concessão de Empréstimos e Financiamentos', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '454041', 'nome' => 'Contribuições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '454042', 'nome' => 'Auxílios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '454064', 'nome' => 'Aquisição de Títulos Representativos de Investimento já Integralizado', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '454066', 'nome' => 'Concessão de Empréstimos e Financiamentos', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '455066', 'nome' => 'Concessão de Empréstimos e Financiamentos', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '458066', 'nome' => 'Concessão de Empréstimos e Financiamentos', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459027', 'nome' => 'Encargos pela Honra de Avais, Garantias, Seguros e Similares', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459061', 'nome' => 'Aquisição de Imóveis', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459062', 'nome' => 'Aquisição de Produtos para Revenda', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459063', 'nome' => 'Aquisição de Títulos de Crédito', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459064', 'nome' => 'Aquisição de Títulos Representativos de Investimento já Integralizado', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459065', 'nome' => 'Constituição ou Aumento de Investimento de Empresas', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459066', 'nome' => 'Concessão de Empréstimos e Financiamentos', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459067', 'nome' => 'Depósitos Compulsórios', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459091', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459093', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459147', 'nome' => 'Obrigações Tributárias e Contributivas', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459161', 'nome' => 'Aquisição de Imóveis', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459162', 'nome' => 'Aquisição de Produtos para Revenda', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459166', 'nome' => 'Concessão de Empréstimos e Financiamentos', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459191', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '459192', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469071', 'nome' => 'Principal da Dívida Contratual Resgatado', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469072', 'nome' => 'Principal da Dívida Mobiliária Resgatado', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469073', 'nome' => 'Correção Monetária ou Cambial da Dívida Contratual Resgatada', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469074', 'nome' => 'Correção Monetária ou Cambial da Dívida Mobiliária Resgatada', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469075', 'nome' => 'Correção Monetária da Dívida de Operações de Crédito por Antecipação da Receita', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469076', 'nome' => 'Principal Corrigido da Dívida Mobiliária Refinanciado', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469077', 'nome' => 'Principal Corrigido da Dívida Contratual Refinanciado', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469091', 'nome' => 'Sentenças Judiciais', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469092', 'nome' => 'Despesas de Exercícios Anteriores', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '469093', 'nome' => 'Indenizações e Restituições', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '339000', 'nome' => '339000', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319100', 'nome' => '319100', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '319000', 'nome' => '319000', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '449000', 'nome' => '449000', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '339100', 'nome' => '339100', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '997202', 'nome' => '997202', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '421292', 'nome' => '421292', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '131801', 'nome' => '131801', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '997204', 'nome' => '997204', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '131100', 'nome' => '131100', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '139000', 'nome' => '139000', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '142000', 'nome' => '142000', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '160013', 'nome' => '160013', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '160016', 'nome' => '160016', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '180000', 'nome' => '180000', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '421202', 'nome' => '421202', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '421218', 'nome' => '421218', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '335000', 'nome' => '335000', 'tipo' => 'Custeio' ]);
NaturezaDespesa::create([ 'codigo' => '141000', 'nome' => '141000', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '192299', 'nome' => '192299', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '121999', 'nome' => '121999', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '131808', 'nome' => '131808', 'tipo' => '' ]);
NaturezaDespesa::create([ 'codigo' => '421191', 'nome' => '421191', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '421235', 'nome' => '421235', 'tipo' => 'Investimento' ]);
NaturezaDespesa::create([ 'codigo' => '131810', 'nome' => '131810', 'tipo' => '' ]);
    }
}
